### ISSUE TITLE
Catalog : unable to query or drop incomplete table

### ISSUE THREAD

**Issue by elenaviter** [ImpalaToGo/ImpalaToGo#49]
Related loglines from **catalogd** to signal the table is malformed:
```bash
I0312 13:57:15.250871 16837 TableLoader.java:91] error loading table. incomplete table is assigned for : tpcds1_item_p
```

Related loglines from **shell**:
```bash
> drop table tpcds1_item_p;
Query: drop table tpcds1_item_p
ERROR: AnalysisException: Table does not exist: default.tpcds1_item_p
```

**Comment by elenaviter** [comment]
This issue may be resolved only for single Impala Catalog session due to Hive metastore specifics in regards to deletion of tables with StorageDescriptor.
Such tables are tried to be removed involving original filesystem where table is pinned (even if "delete data" flag is set to false while table deletion).
```bash
org.apache.hadoop.hive.metastore.HiveMetaStore:
1456    private List<Path> More ...dropPartitionsAndGetLocations(RawStore ms, String dbName,
1457      String tableName, Path tablePath, List<FieldSchema> partitionKeys, boolean checkLocation)
...
1463      if (tablePath != null) {
1464        tableDnsPath = wh.getDnsPath(tablePath);
1465      }
```

Here, getDnsPath() will try to connect original FS (which is not available) and will rise an exception on top

```bash
c2-54-237-79-230.compute-1.amazonaws.com/10.167.74.169:19998 after 0 attempts)
	at org.apache.hadoop.hive.metastore.MetaStoreUtils.logAndThrowMetaException(MetaStoreUtils.java:1116)
	at org.apache.hadoop.hive.metastore.Warehouse.getFs(Warehouse.java:110)
	at org.apache.hadoop.hive.metastore.Warehouse.getDnsPath(Warehouse.java:140)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.dropPartitionsAndGetLocations(HiveMetaStore.java:1473)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.drop_table_core(HiveMetaStore.java:1383)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.drop_table_with_environment_context(HiveMetaStore.java:1525)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invoke(RetryingHMSHandler.java:106)
	at com.sun.proxy.$Proxy9.drop_table_with_environment_context(Unknown Source)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.dropTable(HiveMetaStoreClient.java:785)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.dropTable(HiveMetaStoreClient.java:761)
	at com.cloudera.impala.service.CatalogOpExecutor$2.dowork(CatalogOpExecutor.java:1038)
	at com.cloudera.impala.service.CatalogOpExecutor$2.dowork(CatalogOpExecutor.java:1033)
	at com.cloudera.impala.common.InterruptableCallable.call(InterruptableCallable.java:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

This is a bug in deletion table "without data" in hive metastore.

Current bug will be closed from impala side as "drop table is possible but it only influences Catalog current state, so table will only be dropped from Catalog registry"
