### ISSUE TITLE
Problem with insert ... select

### ISSUE THREAD

**Issue by DavidGruzman** [ImpalaToGo/ImpalaToGo#70]
For big data set we get "entity too large" error:  Actual files in our cache where 13 GB....

org.apache.hadoop.fs.s3.S3Exception: org.jets3t.service.S3ServiceException: S3 Error Message. -- ResponseCode: 400, ResponseStatus: Bad Request, XML Error Message: <?xml version="1.0" encoding="UTF-8"?><Error><Code>EntityTooLarge</Code><Message>Your proposed upload exceeds the maximum allowed size</Message><ProposedSize>13023185158</ProposedSize><MaxSizeAllowed>5368709120</MaxSizeAllowed><RequestId>C32ECFDC830B87CA</RequestId><HostId>4hYxCXccdLeK0NVm2VSR9wuPTQcZu78dS2YWt17smgw1+B1LaCvuOC+eHbFrH6EkyKjr/xJN+tc=</HostId></Error>
        at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.processException(Jets3tNativeFileSystemStore.java:464)
        at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.handleException(Jets3tNativeFileSystemStore.java:411)
        at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.storeFile(Jets3tNativeFileSystemStore.java:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
        at org.apache.hadoop.fs.s3native.$Proxy10.storeFile(Unknown Source)
        at org.apache.hadoop.fs.s3native.NativeS3FileSystem$NativeS3FsOutputStream.close(NativeS3FileSystem.java:275)
        at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
        at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)

**Comment by DavidGruzman** [comment]
Taking into account that we can not split files indied our cache - it would be much better to be able to create more smaller files. We have to check if there is a way to control size of created files

**Comment by elenaviter** [comment]
Could be handled on s3n using following configuration:
1. **hdfs-site.xml:**
  ```xml
  <property>
    <name>fs.s3n.multipart.uploads.enabled</name>
    <value>true</value>
    <description>Setting this property to true enables multiple uploads to
  native S3 filesystem. When uploading a file, it is split into blocks
  if the size is larger than fs.s3n.multipart.uploads.block.size.
    </description>
 </property>
 <property>
   <name>fs.s3n.multipart.uploads.split.size</name>
   <value>524288000</value>
   <description>
   </description>
</property>
<property>
  <name>fs.s3n.multipart.uploads.block.size</name>
  <value>67108864</value>
  <description>The block size for multipart uploads to native S3 filesystem.
  Default size is 64MB.
  </description>
</property>
<property>
  <name>fs.s3n.multipart.copy.block.size</name>
  <value>5368709120</value>
  <description>The block size for multipart copy in native S3 filesystem.
  Default size is 5GB.
  </description>
</property>
  ```

1. Create the file **/etc/hadoop/conf/jets3t.properties** with following content (number of threads in threaded service = 1 is mandatory):

  ```sh
  storage-service.internal-error-retry-max=5
  storage-service.disable-live-md5=false
  threaded-service.max-thread-count=1
  threaded-service.admin-max-thread-count=1
  s3service.max-thread-count=20
  s3service.admin-max-thread-count=20
  ```
